---
title: "STAT_325_Final"
author: "Dilan Fajardo"
output:
  pdf_document:
    latex_engine: xelatex
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(car)
library(lmtest)
library(MASS)
data <- read.csv("C:\\Users\\dilan\\Downloads\\Life Expectancy Data.csv")

data <- data %>%
  drop_na(Life.expectancy, Hepatitis.B, Polio, Diphtheria, GDP, Status, percentage.expenditure)

developing <- data %>%
  filter(Status == "Developing")

developed <- data %>%
  filter(Status == "Developed")
```

```{r}
summary_stats <- data.frame(
  Variable = c("Life.expectancy", "Hepatitis.B", "Polio", "Diphtheria", "percentage.expenditure"),
  Mean = c(
    mean(developing$Life.expectancy, na.rm = TRUE),
    mean(developing$Hepatitis.B, na.rm = TRUE),
    mean(developing$Polio, na.rm = TRUE),
    mean(developing$Diphtheria, na.rm = TRUE),
    mean(developing$percentage.expenditure, na.rm = TRUE)
  ),
  SD = c(
    sd(developing$Life.expectancy, na.rm = TRUE),
    sd(developing$Hepatitis.B, na.rm = TRUE),
    sd(developing$Polio, na.rm = TRUE),
    sd(developing$Diphtheria, na.rm = TRUE),
    sd(developing$percentage.expenditure, na.rm = TRUE)
  )
)

summary_stats

summary_stats2 <- data.frame(
  Variable = c("Life.expectancy", "Hepatitis.B", "Polio", "Diphtheria", "percentage.expenditure"),
  Mean = c(
    mean(developed$Life.expectancy, na.rm = TRUE),
    mean(developed$Hepatitis.B, na.rm = TRUE),
    mean(developed$Polio, na.rm = TRUE),
    mean(developed$Diphtheria, na.rm = TRUE),
    mean(developed$percentage.expenditure, na.rm = TRUE)
  ),
  SD = c(
    sd(developed$Life.expectancy, na.rm = TRUE),
    sd(developed$Hepatitis.B, na.rm = TRUE),
    sd(developed$Polio, na.rm = TRUE),
    sd(developed$Diphtheria, na.rm = TRUE),
    sd(developed$percentage.expenditure, na.rm = TRUE)
  )
)

summary_stats2
```

```{r}
#Developing Model 
model1 <- lm(
  Life.expectancy ~ Hepatitis.B + Polio + Diphtheria + percentage.expenditure,
  data = developing
)

summary(model1)

#Check for multicollinearity
vif(model1)

#Normality Assumption 
qqnorm(residuals(model1))
qqline(residuals(model1), col = "red")

#Constant Varince 
bptest(model1)
plot(model1, which = 1)
```

```{r}
#BoxCox transformations 
boxcox(model1)
developing$Life.exp.2 <- (developing$Life.expectancy^2 - 1) / 2

model1_lambda2 <- lm(
  Life.exp.2 ~ Hepatitis.B + Polio + Diphtheria + percentage.expenditure,
  data = developing
)

summary(model1_lambda2)

#Normality Assumption 
# QQ plot
qqnorm(residuals(model1_lambda2))
qqline(residuals(model1_lambda2), col = "red")

#Constant Variance 
plot(model1_lambda2, which = 1)

#Multicollieanrity 
vif(model1_lambda2)
```
```{r}
#Log Transformation 
developing$Life.exp.log <- log(developing$Life.expectancy)

model_log <- lm(
  Life.exp.log ~ Hepatitis.B + Polio + Diphtheria + percentage.expenditure,
  data = developing
)

summary(model_log)

#Diagnostics
qqnorm(residuals(model_log)); qqline(residuals(model_log), col="red")
plot(model_log, which = 1)
vif(model_log)

```
```{r}
#Square Transformation 
developing$Life.exp.sqrt <- sqrt(developing$Life.expectancy)

model_sqrt <- lm(
  Life.exp.sqrt ~ Hepatitis.B + Polio + Diphtheria + percentage.expenditure,
  data = developing
)

summary(model_sqrt)

#Diagnostics
qqnorm(residuals(model_sqrt)); qqline(residuals(model_sqrt), col="red")
plot(model_sqrt, which = 1)
vif(model_sqrt)
```

```{r}
#Trying Interactions 
model_dev_int <- lm(
  Life.expectancy ~ 
    Hepatitis.B*percentage.expenditure +
    Polio*percentage.expenditure +
    Diphtheria*percentage.expenditure,
  data = developing
)

summary(model_dev_int)
#Normality Assumption 
# QQ plot
qqnorm(residuals(model_dev_int))
qqline(residuals(model_dev_int), col = "red")

#Constant Variance 
plot(model_dev_int, which = 1)

vif(model_dev_int)

```

```{r}
#Developed Model
model2 <- lm(
  Life.expectancy ~ Hepatitis.B + Polio + Diphtheria + percentage.expenditure,
  data = developed
)

summary(model2)

#Multicollinearity 
vif(model2)

#Normality
qqnorm(residuals(model2))
qqline(residuals(model2), col = "red")

#Constant variance 
plot(model2, which = 1)

```